version: '3.5'

services:
  app:
    build: .
    ports:
      - 4000:4000
    container_name: ex-mon
    volumes:
      - '.:/usr/src/app'
      - studying-elixir:/root/.mix
    # depends_on:
    #   - pgsqldb
  pgsqldb:
    image: postgres:9.6
    container_name: "pgsqldb"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ex_mon_api_dev"
      TZ: "GMT"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "15432:5432"
    # networks:
    #   default:
    #     ipv4_address: 172.50.1.30

volumes:
  studying-elixir:

networks:
  default:
    external:
      name: Xmon

